# Generated by Django 5.2.5 on 2025-10-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_admintbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admintbl',
            old_name='password',
            new_name='admin_password',
        ),
        migrations.RenameField(
            model_name='admintbl',
            old_name='username',
            new_name='admin_username',
        ),
    ]
