# Generated by Django 5.2.5 on 2025-10-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_password_admintbl_admin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signtbl',
            name='email_login',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
