# Generated by Django 5.2.5 on 2025-10-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_notice_options_remove_notice_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_id',
        ),
        migrations.AddField(
            model_name='notice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
